name: Flutter CI

on: push

jobs:
  build-and-release-windows:
    runs-on: windows-latest
    
    steps:
        - uses: actions/checkout@v2
        - uses: subosito/flutter-action@v1
          with:
            channel: 'stable'
            flutter-version: '3.19.2'
        - name: Install project dependencies
          run: flutter pub get
        - name: Generate intermediates
          run: flutter pub run build_runner build --delete-conflicting-outputs
        - name: Enable windows build
          run: flutter config --enable-windows-desktop
        - name: Build artifacts
          run: flutter build windows --release
        - name: Archive Release
          uses: thedoctor0/zip-release@master
          with:
            type: 'zip'
            filename: coom-dl-${{github.ref_name}}-windows.zip
            directory: build/windows/x64/runner/Release
        - name: Artifacts Release
          uses: actions/upload-artifact@4
          if: startsWith(github.ref, 'refs/tags/')
          with:
            name: coom-dl-${{github.ref_name}}-windows.zip
            path: build/windows/x64/runner/Release/